language: java

jdk: openjdk13

os: windows

services: postgresql

after_success: bash <(curl -s https://codecov.io/bash)

before_install: psql -c 'create database tracker;' -U postgres

notifications:
  email:
    recipients:
      kirbel74@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global: CODECOV_TOKEN="1695516b-ae96-4dfb-9f98-ffc18741de57"