language: java

jdk: openjdk13

services: postgresql

after_success: bash <(curl -s https://codecov.io/bash)


before_install: psql -c 'create database tracker;' -U postgres

notifications:
  email:
    recipients:
      kirbel74@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global: CODECOV_TOKEN="510b8e4e-a858-40e3-ad52-204ed6695780"